# Generated by Django 5.1.2 on 2024-10-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('type', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('admin', 'Admin')], default='free', max_length=10)),
            ],
        ),
    ]
