# Generated by Django 5.1.2 on 2024-10-31 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_recoverytoken_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[("free", "Free"), ("premium", "Premium"), ("admin", "Admin")],
                default="free",
                max_length=10,
                verbose_name="tipo de conta",
            ),
        ),
    ]
