# Generated by Django 5.1.2 on 2024-10-28 14:53

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_alter_recoverytoken_value"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0.0, max_digits=10, verbose_name="saldo"
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="cpf",
            field=models.CharField(max_length=11, unique=True, verbose_name="CPF"),
        ),
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[("free", "Free"), ("premium", "Premium"), ("admin", "Admin")],
                default=account.models.AccountType["FREE"],
                max_length=10,
                verbose_name="tipo de conta",
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="username",
            field=models.CharField(max_length=100, verbose_name="nome de usuário"),
        ),
    ]
