# Generated by Django 5.1.2 on 2024-11-03 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flag",
            name="name",
            field=models.CharField(max_length=100, unique=True, verbose_name="nome"),
        ),
    ]
