stages:
  - deploy

deploy:
  stage: deploy
  script:
    # Crie o arquivo de chave SSH a partir da variável EC2_KEY
    - echo "$EC2_KEY" > ec2_key.pem
    - chmod 600 ec2_key.pem
    
    # Envia o código para a EC2
    - scp -o StrictHostKeyChecking=no -i ec2_key.pem -r . $EC2_USER@$EC2_HOST:/home/ubuntu/app/

    # Conecte-se à EC2 e execute o Docker Compose Plugin
    - ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
        cd /home/ubuntu/app/
        docker compose down
        docker compose up -d --build
      EOF
  only:
    - develop
