stages:
  - deploy

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh  # Apenas SSH
  script:
    - echo "$EC2_KEY" > ec2_key.pem
    - chmod 600 ec2_key.pem

    # Envia todo o conteúdo, exceto o diretório .git
    - scp -o StrictHostKeyChecking=no -i ec2_key.pem -r ./* $EC2_USER@$EC2_HOST:/home/ubuntu/app/

    # Conecte-se à EC2 e execute o Docker Compose Plugin
    - ssh -o StrictHostKeyChecking=no -i ec2_key.pem $EC2_USER@$EC2_HOST << 'EOF'
        cd /home/ubuntu/app/ && docker compose down && docker compose up -d --build
      EOF
  only:
    - develop
