# Generated by Django 5.1.2 on 2024-10-30 01:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInvestment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('tax', models.DecimalField(decimal_places=2, help_text='Taxa anual do produto', max_digits=5, verbose_name='taxa anual')),
                ('start_date', models.DateField(verbose_name='data de início')),
                ('end_date', models.DateField(verbose_name='data final')),
                ('minimum_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor mínimo')),
                ('is_premium', models.BooleanField(default=False, verbose_name='premium')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accumulated_income', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('investment_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('rescue_data', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('resgatado', 'Resgatado'), ('vencido', 'Vencido')], default='ativo', max_length=10)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investments.productinvestment')),
            ],
        ),
    ]
