# Generated by Django 5.1.2 on 2024-11-03 22:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Indexer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductInvestment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="nome")),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Taxa anual do produto",
                        max_digits=5,
                        verbose_name="taxa administrativa anual",
                    ),
                ),
                (
                    "index_multiplier",
                    models.DecimalField(
                        decimal_places=2,
                        default=1,
                        help_text="Multiplicador do indexador",
                        max_digits=5,
                        verbose_name="Multiplicador do indexador",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                (
                    "final_date",
                    models.DateTimeField(
                        default=datetime.datetime(2025, 2, 3, 22, 17, 2, 620625)
                    ),
                ),
                (
                    "minimum_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="valor mínimo"
                    ),
                ),
                (
                    "is_premium",
                    models.BooleanField(default=False, verbose_name="premium"),
                ),
                (
                    "indexer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investments.indexer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Investment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applied_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "accumulated_income",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("initial_date", models.DateTimeField(auto_now_add=True)),
                ("rescue_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativo", "Ativo"),
                            ("resgatado", "Resgatado"),
                            ("vencido", "Vencido"),
                        ],
                        default="ativo",
                        max_length=10,
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="investments.productinvestment",
                    ),
                ),
            ],
        ),
    ]
