# Generated by Django 5.1.2 on 2024-11-02 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinvestment',
            name='final_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 2, 22, 32, 55, 722220, tzinfo=datetime.timezone.utc)),
        ),
    ]
