# Generated by Django 5.1.2 on 2024-11-03 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_alter_productinvestment_final_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinvestment',
            name='final_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 3, 19, 25, 43, 74250)),
        ),
    ]
