# Generated by Django 5.1.2 on 2024-10-29 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_productinvestment_range_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinvestment',
            name='end_date',
        ),
        migrations.AddField(
            model_name='investment',
            name='investment_validate_data',
            field=models.DateField(default=datetime.date(2024, 10, 29)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='investment_data',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='rescue_data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
