# Generated by Django 5.1.2 on 2024-11-03 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_productinvestment_final_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinvestment',
            name='final_date',
            field=models.DateTimeField(),
        ),
    ]
