# Generated by Django 5.1.2 on 2024-10-29 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_remove_productinvestment_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='investment_validate_data',
            new_name='due_date',
        ),
        migrations.RenameField(
            model_name='investment',
            old_name='investment_data',
            new_name='initial_date',
        ),
    ]
