# Generated by Django 5.1.2 on 2024-10-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_rename_investment_validate_data_investment_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinvestment',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='premium'),
        ),
        migrations.AlterField(
            model_name='indexer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productinvestment',
            name='minimum_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='valor mínimo'),
        ),
        migrations.AlterField(
            model_name='productinvestment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome'),
        ),
        migrations.AlterField(
            model_name='productinvestment',
            name='tax',
            field=models.DecimalField(decimal_places=2, help_text='Taxa anual do produto', max_digits=5, verbose_name='taxa anual'),
        ),
    ]
