# Generated by Django 5.1.2 on 2024-10-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_productinvestment_is_premium_alter_indexer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexer',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
