# Generated by Django 5.1.2 on 2024-10-31 02:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_remove_productinvestment_range_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinvestment',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 2, 13, 10, 401566, tzinfo=datetime.timezone.utc)),
        ),
    ]
