# Generated by Django 5.1.2 on 2024-10-31 02:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0008_alter_productinvestment_final_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='productinvestment',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 2, 37, 22, 173081, tzinfo=datetime.timezone.utc)),
        ),
    ]
