# Generated by Django 5.1.2 on 2024-10-31 03:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0009_remove_investment_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinvestment',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 3, 11, 33, 841080, tzinfo=datetime.timezone.utc)),
        ),
    ]
