# Generated by Django 5.1.2 on 2024-10-31 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0010_alter_productinvestment_final_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinvestment',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 3, 16, 24, 492750, tzinfo=datetime.timezone.utc)),
        ),
    ]
