# Generated by Django 5.1.2 on 2024-10-31 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0007_alter_productinvestment_index_multiplier_and_more'),
        ('investments', '0011_alter_productinvestment_final_date'),
    ]

    operations = [
    ]
