# Generated by Django 5.1.2 on 2024-10-31 14:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0012_merge_20241031_1432"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinvestment",
            name="final_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 1, 31, 14, 32, 16, 22183, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
