# Generated by Django 5.1.2 on 2024-10-31 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_alter_productinvestment_final_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='investment',
            old_name='rescue_data',
            new_name='rescue_date',
        ),
        migrations.AlterField(
            model_name='productinvestment',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 17, 16, 21, 343859, tzinfo=datetime.timezone.utc)),
        ),
    ]
