# Generated by Django 5.1.2 on 2024-10-31 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0015_alter_productinvestment_final_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinvestment",
            name="final_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 1, 31, 14, 38, 45, 151921, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
