# Generated by Django 5.1.2 on 2024-11-01 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0025_alter_productinvestment_final_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='rescue_data',
        ),
        migrations.AddField(
            model_name='investment',
            name='rescue_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productinvestment',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 1, 15, 37, 4, 646979, tzinfo=datetime.timezone.utc)),
        ),
    ]
