# Generated by Django 5.1.2 on 2024-10-31 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0012_merge_20241031_1116'),
        ('investments', '0014_rename_rescue_data_investment_rescue_date_and_more'),
        ('investments', '0025_alter_productinvestment_final_date'),
    ]

    operations = [
    ]
