# Generated by Django 5.1.2 on 2024-11-01 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0026_merge_20241101_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinvestment',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 1, 14, 58, 35, 878863, tzinfo=datetime.timezone.utc)),
        ),
    ]
