# Generated by Django 5.1.2 on 2024-11-01 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "investments",
            "0026_remove_investment_rescue_data_investment_rescue_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="productinvestment",
            name="final_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 1, 21, 14, 19, 651267, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
