# Generated by Django 5.1.2 on 2024-11-02 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0027_alter_productinvestment_final_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='initial_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='investment',
            name='rescue_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productinvestment',
            name='final_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 2, 17, 35, 37, 396584, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='productinvestment',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
