# Generated by Django 5.1.2 on 2024-11-02 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("investments", "0027_alter_productinvestment_final_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="rescue_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="productinvestment",
            name="final_date",
            field=models.DateField(
                default=datetime.datetime(
                    2025, 2, 2, 0, 42, 20, 44254, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
