# Generated by Django 5.1.2 on 2024-11-02 09:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0028_alter_investment_rescue_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinvestment',
            name='final_date',
            field=models.DateField(default=datetime.datetime(2025, 2, 2, 9, 34, 34, 234475, tzinfo=datetime.timezone.utc)),
        ),
    ]
