# Generated by Django 5.1.2 on 2024-11-02 19:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0028_alter_investment_initial_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinvestment',
            name='final_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 2, 19, 21, 29, 780443, tzinfo=datetime.timezone.utc)),
        ),
    ]
