# Generated by Django 5.1.2 on 2024-10-22 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0002_alter_account_cpf_alter_account_email_and_more"),
        ("group", "0002_group_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="accounts",
            field=models.ManyToManyField(
                blank=True, related_name="group", to="Account.account"
            ),
        ),
    ]
